export const ON_LOGIN = 'ON_LOGIN';
export const ON_GET_DATA_RESPONSE = 'ON_GET_DATA_RESPONSE'
export const ON_GET_VENUE_DATA_RESPONSE = 'ON_GET_VENUE_DATA_RESPONSE'
export const ON_GET_VENUE_DATA_REQUEST = 'ON_GET_VENUE_DATA_REQUEST'

export type ON_LOGIN = typeof ON_LOGIN;
export type ON_GET_DATA_RESPONSE = typeof ON_GET_DATA_RESPONSE;
export type ON_GET_VENUE_DATA_RESPONSE = typeof ON_GET_VENUE_DATA_RESPONSE;
export type ON_GET_VENUE_DATA_REQUEST = typeof ON_GET_VENUE_DATA_REQUEST;