export const ON_LOGIN = 'ON_LOGIN';
export const GET_DATA_RESPONSE = 'GET_DATA_RESPONSE'
export const GET_VENUE_DATA_RESPONSE = 'GET_VENUE_DATA_RESPONSE'
export const GET_VENUE_DATA_REQUEST = 'GET_VENUE_DATA_REQUEST'

export type ON_LOGIN = typeof ON_LOGIN;
export type GET_DATA_RESPONSE = typeof GET_DATA_RESPONSE;
export type GET_VENUE_DATA_RESPONSE = typeof GET_VENUE_DATA_RESPONSE;
export type GET_VENUE_DATA_REQUEST = typeof GET_VENUE_DATA_REQUEST;